### PR TITLE
Improved connectivity check

### LINKED ISSUE #2: Improve connectivity check
The app shouldn't work on 4G network with no data or WiFi network with no WAN access
// cc @SDIDSA

### LINKED ISSUE #3: Password input placeholder
Pretty self explanatory

### PR DESCRIPTION
**Pull request by SDIDSA**
more code refactoring, the connectivity check will happen on the main activity on load in 2 steps

1. checks if WiFi or mobile network is connected, if nothing it opens the NoInternet Activity, else it goes to step 2
2. sends a post to google.com, if it times out it opens the NoInternet Activity, if it return a 405 it opens the login form

### important changes : 

- fixed the password placeholder
- the connectivity check code moved to a separate class ConnectivityCheck which can be called from anywhere in the app to check if the phone is still connected
- added reconnect button in the NoInternet Activity to re-run the connectivity check and go back to the MainActivity if it succeeds
- added the alert package (based on the Popup class) and introduced AlertTypes (CONFIRMATION & INFORMATION), alerts can be used all around the app for a variety of purposes

### CODE REVIEW

**Comment by CaddyDz** [comment]
> the connectivity check will happen on the main activity

Does this mean that the app can't be opened at all without internet connection?

i.e should be able to open offline if user already has token stored

**Comment by SDIDSA** [comment]
yes, it will stop at NoInternet activity if there is no internet, i think this problem is included with #4 , should i fix it in this PR or with #4  ?

**Comment by CaddyDz** [comment]
I don't think it has anything to do with #4 , it's a separate issue, thought it was already working offline and you changed that

**Comment by SDIDSA** [comment]
i see, will fix it and commit shortly

**Review by CaddyDz — APPROVED** [review]
LGTM!

**Pull request merged**
